workspace 'Top250Movies.xcworkspace'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'RealmSwift'
end

xcodeproj 'Top250Movies.xcodeproj'
xcodeproj 'NetworkAPI.xcodeproj'

target :Top250Movies do
  xcodeproj 'Top250Movies'
  shared_pods
  pod 'Kingfisher', '~> 7.0'
  
  target 'Top250MoviesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Top250MoviesUITests' do
    # Pods for testing
  end
end

target :NetworkAPI do
  xcodeproj 'NetworkAPI.xcodeproj'
  shared_pods
end
